apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-pubsub
  labels:
    app: ros-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-pubsub
  template:
    metadata:
      labels:
        app: ros-pubsub
    spec:
      containers:
        - name: publisher
          image: bmt45/pubsub:latest
          command: ["/rover_ws/scripts/start_publisher.sh"]
          
        - name: subscriber
          image: bmt45/pubsub:latest
          command: ["/rover_ws/scripts/start_subscriber.sh"]
